//encoder motor i.e.shoulders
#define flleg_phaseA 2
#define flleg_phaseB 4
#define flleg_mtr 5
#define flleg_kp 100
#define flleg_ki 100
#define flleg_kd 100
#define frleg_phaseA 3
#define frleg_phaseB 7
#define frleg_mtr 8
#define frleg_kp 100
#define frleg_ki 100
#define frleg_kd 100
#define blleg_phaseA 18
#define blleg_phaseB 10
#define blleg_mtr 11
#define blleg_kp 100
#define blleg_ki 100
#define blleg_kd 100
#define brleg_phaseA 19
#define brleg_phaseB 13
#define brleg_mtr 14
#define brleg_kp 100
#define brleg_ki 100
#define brleg_kd 100
#define motor1 1
#define motor2 2
#define motor3 3
#define motor4 4

//servo motor i.e.knee
#define flknee_pin 1
#define frknee_pin 16
#define blknee_pin 17
#define brknee_pin 20

//general
#define servo_initangle 0
#define servo_finangle 30
#define encoder_initangle 0
#define encoder_finangle 60
#define activate_pin 21
#define set_delay 300
#define x1 40
#define y1 20
#define initial1 13
#define initial2 0
#define dly 200
#define walkpin 22
