//encoder motor i.e.shoulders
#define flleg_phaseA 2
#define flleg_phaseB 22
#define flleg_mtr1 4
#define flleg_mtr2 5
#define flleg_kp 5
#define flleg_ki 0
#define flleg_kd 0
#define frleg_phaseA 3
#define frleg_phaseB 23
#define frleg_mtr1 6
#define frleg_mtr2 7
#define frleg_kp 100
#define frleg_ki 100
#define frleg_kd 100
#define blleg_phaseA 18
#define blleg_phaseB 24
#define blleg_mtr1 8
#define blleg_mtr2 9
#define blleg_kp 100
#define blleg_ki 100
#define blleg_kd 100
#define brleg_phaseA 19
#define brleg_phaseB 25
#define brleg_mtr1 10
#define brleg_mtr2 11
#define brleg_kp 100
#define brleg_ki 100
#define brleg_kd 100

//servo motor i.e.knee
#define flknee_pin 26
#define frknee_pin 27
#define blknee_pin 28
#define brknee_pin 29

//general
#define servo_initangle 0
#define servo_finangle 30
#define encoder_initangle 100
#define encoder_finangle 200
#define activate_pin 21
#define set_delay 300
#define x1 40
#define y1 20
#define initial1 13
#define initial2 0
#define dly 200
#define walkpin 1
