#define flleg_phaseA 2
#define flleg_phaseB 4
#define flleg_mtr1 5
#define flleg_mtr2 6
#define flleg_kp 100
#define flleg_ki 100
#define flleg_kd 100
#define frleg_phaseA 3
#define frleg_phaseB 7
#define frleg_mtr1 8
#define frleg_mtr2 9
#define frleg_kp 100
#define frleg_ki 100
#define frleg_kd 100
#define blleg_phaseA 18
#define blleg_phaseB 10
#define blleg_mtr1 11
#define blleg_mtr2 12
#define blleg_kp 100
#define blleg_ki 100
#define blleg_kd 100
#define brleg_phaseA 19
#define brleg_phaseB 13
#define brleg_mtr1 14
#define brleg_mtr2 15
#define brleg_kp 100
#define brleg_ki 100
#define brleg_kd 100
#define flknee_pin 1
#define frknee_pin 16
#define blknee_pin 17
#define brknee_pin 20
#define servo_initangle 10
#define encoder_initangle 0
#define encoder_finangle 0
#define servo_finangle 0
#define activate_pin 21
